// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

module.exports = {
  aws_project_region: "ap-southeast-2",
  aws_appsync_graphqlEndpoint:
    "https://ygn3gw4fprb2ta4dvrrq3hfckq.appsync-api.ap-southeast-2.amazonaws.com/graphql",
  aws_appsync_region: "ap-southeast-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_secretId: "staging-appsync-api-key",
};
